// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH2y59Rq0Qw38NHKSCvJo72wOAhUsLIx8',
    appId: '1:1046332415691:web:59cb11e9b57cad7a85854e',
    messagingSenderId: '1046332415691',
    projectId: 'manager-8651f',
    authDomain: 'manager-8651f.firebaseapp.com',
    storageBucket: 'manager-8651f.firebasestorage.app',
    measurementId: 'G-23LNMQ8XVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Hl_rJzjbV5_Nn-z_9Nq_j7Jp8nKmCDo',
    appId: '1:1046332415691:android:f6d9297f3c68edb485854e',
    messagingSenderId: '1046332415691',
    projectId: 'manager-8651f',
    storageBucket: 'manager-8651f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB_miYuWqogLIvVTXsyI6iW4win6BLrqI',
    appId: '1:1046332415691:ios:89dd88491fcf146485854e',
    messagingSenderId: '1046332415691',
    projectId: 'manager-8651f',
    storageBucket: 'manager-8651f.firebasestorage.app',
    iosBundleId: 'com.example.manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB_miYuWqogLIvVTXsyI6iW4win6BLrqI',
    appId: '1:1046332415691:ios:89dd88491fcf146485854e',
    messagingSenderId: '1046332415691',
    projectId: 'manager-8651f',
    storageBucket: 'manager-8651f.firebasestorage.app',
    iosBundleId: 'com.example.manager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH2y59Rq0Qw38NHKSCvJo72wOAhUsLIx8',
    appId: '1:1046332415691:web:108543010bfe246c85854e',
    messagingSenderId: '1046332415691',
    projectId: 'manager-8651f',
    authDomain: 'manager-8651f.firebaseapp.com',
    storageBucket: 'manager-8651f.firebasestorage.app',
    measurementId: 'G-VJB29L60JY',
  );
}
